- name: Play1
  hosts: FrontEnd
  tasks:
  - name: Hello from Paly1 and Task1
    ansible.builtin.debug:
      msg: "Hello from Play1 and Task1"

  - name: Hello from Play1 and Task2
    ansible.builtin.debug:
      msg: "Hello from Play1 and Task2"


- name: Play2
  hosts: FrontEnd
  tasks:
  - name: Hello from Paly2 and Task1
    ansible.builtin.debug:
      msg: "Hello from Play2 and Task1"

  - name: Hello from Play2 and Task2
    ansible.builtin.debug:
      msg: "Hello from Play2 and Task2"
