- name: Promt Vars
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: Please enter the username
    private: true

  - name: passowrd
    prompt: Please enter the passowrd
    private: true
  tasks:
  - name: Printing user Information
    ansible.builtin.debug:
      msg: "Hell, Your UserName is: {{ username}} and Password is {{ password }}"
  