- name: Playbook cntrol using ansible facts
  hosts: FrontEnd
  become: yes
  tasks:
  - name: install nginx if RedHat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"
  
  - name: install nginx if Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"

  - name: Starting nginx Service
    ansible.builtin.service:
      name: naginx
      state: started
      enabled: yes