- name: Install Packages
  hosts: FrontEnd
  become: yes
  tasks:
  - name: install "{{ item }}"
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - zip