- name: creating user
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user is created or not.
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true
    

  - name: creating roboshop user
    become: yes
    ansible.builtin.command: useradd roboshop
    when: user_output.rc != 0

  - name: User already created
    ansible.builtin.debug:
      msg: "User is Already created: {{ user_output}}"
    when: user_output.rc == 0