- name: Instaaling nginx
  hosts: dynamic_frontend
  become: yes
  serial: 2
  tasks:
  - name: Install nginx S/W
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: Starting service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
