- name: Creating Soft Link
  hosts: local
  connection: local
  tasks:
  - name: Create a symbolic link
    ansible.builtin.file:
      src: /home/ec2-user/manchem/file.txt
      dest: /home/ec2-user/manchem/file1.txt
      state: link